package org.romaframework.module.users.repository;

import java.util.List;

import org.romaframework.aspect.persistence.PersistenceAspect;
import org.romaframework.aspect.persistence.QueryByFilter;
import org.romaframework.core.repository.PersistenceAspectRepository;
import org.romaframework.module.users.domain.BaseGroup;
import org.romaframework.module.users.domain.Realm;

/**
 * Repository class for BaseGroup entity. By default it extends the PersistenceAspectRepository class that delegates the execution
 * of all commands to the PersistenceAspect. <br/>
 * <br/>
 * This class was generated by Roma Meta Framework CRUD wizard.
 */
public class BaseGroupRepository extends PersistenceAspectRepository<BaseGroup> {
	public List<BaseGroup> findByRealm(Realm iRealm) {
		QueryByFilter query = new QueryByFilter(BaseGroup.class);
		query.setStrategy(PersistenceAspect.STRATEGY_DETACHING);
		query.addItem("realm", QueryByFilter.FIELD_EQUALS, iRealm);
		return findByCriteria(query);
	}
}
