package org.romaframework.module.users.repository;

import java.util.List;

import org.romaframework.core.Roma;
import org.romaframework.core.repository.PersistenceAspectRepository;
import org.romaframework.module.admin.domain.Realm;
import org.romaframework.module.users.domain.BaseAccount;
import org.romaframework.module.users.domain.BaseGroup;
import org.romaframework.module.users.domain.BaseProfile;

/**
 * Repository class for BaseGroup entity. By default it extends the PersistenceAspectRepository class that delegates the execution
 * of all commands to the PersistenceAspect. <br/>
 * <br/>
 * This class was generated by Roma Meta Framework CRUD wizard.
 */
public class RealmRepository extends PersistenceAspectRepository<Realm> {

	@Override
	public void delete(Object[] iObjects) {
		for (Object o : iObjects)
			delete((Realm) o);
	}

	@Override
	public void delete(Realm iRealm) {
		// DELETE ACCOUNTS
		List<BaseAccount> accounts = Roma.component(BaseAccountRepository.class).findByRealm(iRealm);
		if (accounts != null)
			Roma.component(BaseAccountRepository.class).delete(accounts.toArray());

		// DELETE GROUPS
		List<BaseGroup> groups = Roma.component(BaseGroupRepository.class).findByRealm(iRealm);
		if (groups != null)
			Roma.component(BaseGroupRepository.class).delete(groups.toArray());

		// DELETE PROFILES
		List<BaseProfile> profiles = Roma.component(BaseProfileRepository.class).findByRealm(iRealm);
		if (profiles != null)
			Roma.component(BaseProfileRepository.class).delete(profiles.toArray());

		super.delete(iRealm);
	}
}
